name: Test scripts

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: {}

jobs:
  check-fish:
    name: Check Fish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.launchpad.net:443
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            github.com:443
            packages.microsoft.com:443
            ppa.launchpadcontent.net:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 #v4.3.0
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@21f4211660d98dab80d2b3e83075ff8f43d9c01e #v2.0.20
      - uses: fish-shop/indent-check@501887e2f0be7b4e11f919191dc1213f906ff3f1 #v2.2.66
      - uses: fish-shop/syntax-check@f05543526fbf8d54c074fbaac405c19d34f4c007 #v2.2.65
      - uses: fish-shop/install-plugin@66c5de8230ba6c523af9cd3476deaf90a781c96c #v2.3.68
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@317ae3cf404110a13ec83329877f7f9a2a6b0811 #v2.3.68
