name: Test scripts

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: {}

jobs:
  check-fish:
    name: Check Fish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.launchpad.net:443
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            github.com:443
            packages.microsoft.com:443
            ppa.launchpadcontent.net:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@1fe9930a0c3df719a54b02b7f992e1c650845f17 #v2.0.18
      - uses: fish-shop/indent-check@a6561a7bd9b6f18582cbac55cbaa800b2ebd2802 #v2.2.64
      - uses: fish-shop/syntax-check@08641346757c66cf39f6d2df3d1ff973485d94f4 #v2.2.63
      - uses: fish-shop/install-plugin@4b5577d4c9b2debf7a7b2acb3f04e2a0c636e1e8 #v2.3.66
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@7ba0288f65d9072e025dd304ee103bdebf30ebcc #v2.3.66
