name: Test scripts

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@9d0347ca5777ded4f95e1013413ebba9e49bcc25 #v1.0.55
      - uses: fish-shop/indent-check@9a910db076ffb53d46f6b0dd5bd57d08e18315da #v2.2.44
      - uses: fish-shop/syntax-check@067251ded786aecb35a8f7d72681cb8aa35f28ea #v2.2.43
      - uses: fish-shop/install-plugin@40aedd6f2458be6054a1d22deb83fc49c4e1451a #v2.3.45
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@6d086d20c000f68dd72d90b4233e6f7806246e44 #v2.3.44
