name: Test scripts

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: {}

jobs:
  check-fish:
    name: Check Fish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.launchpad.net:443
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            github.com:443
            packages.microsoft.com:443
            ppa.launchpadcontent.net:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 #v4.3.0
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@625b10d0eb984238cdc3fb683484767f171cc276 #v2.0.19
      - uses: fish-shop/indent-check@3cb4d4204f954d7b211e4fd6248bec8ba9e3c589 #v2.2.65
      - uses: fish-shop/syntax-check@1a1227d2f6e6f6f738c9dc14ef9b2d645da81cab #v2.2.64
      - uses: fish-shop/install-plugin@ee439a7d1490bfc319b8afd0c421152399d43251 #v2.3.67
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@b03dff65abc117692205fe3447f399075008d996 #v2.3.67
