name: Test scripts

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff #v3.0.0
      - uses: fish-shop/install-fish-shell@632c98f13e7c5f9d029e2307d5927932e44d2a40 #v1.0.50
      - uses: fish-shop/indent-check@994d6a2d937dc3922f6ec6b89307b74556852bc7 #v2.2.39
      - uses: fish-shop/syntax-check@57aade2a0622b4a5c18bf304c89a747cd8641360 #v2.2.38
      - uses: fish-shop/install-plugin@810c3dd023e69cca5c4c4e09f48cbe581912f62d #v2.3.40
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@30e980b667c509985a174350062ba0fcce12dc12 #v2.3.38
